### ISSUE TITLE
'ascii' codec can't encode character u'\U0001f4a9' in position 4: ordinal not in range(128)

### ISSUE THREAD

**Issue by jkleve** [nicolargo/glances#1185]
With the wifi module enabled, I get an uncaught exception due to a neighbor's weird wifi name.     

The exact exception I get is:
`UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4a9' in position 4: ordinal not in range(128)`     

The issue is caused from the following line of code (glances_wifi.py:200)
`msg = '{:{width}}'.format(hotspotname, width=ifname_max_width)`    

The cause being that the default encoding for strings when using format is 'ascii'. This won't be able to handle all characters that are allowed in a ssid (i.e. my neighbors wifi which is: Grey💩On) . 

The code could handle this by replacing unknown characters with '?' or by trying to use UTF-8 instead.

**Comment by nicolargo** [comment]
Corrected in the latest commit. Use the standard u() function of the glances.compat script.

**Comment by jkleve** [comment]
This change did not fix this issue. I updated to commit 9c3c4ba on the develop branch and I now get the same exception again.

**Comment by nicolargo** [comment]
@jkleve The update to test is the following: https://github.com/nicolargo/glances/commit/a47bf1a76b948c8ffdf60fcbc0ba1693847beb1b

**Comment by jkleve** [comment]
@nicolargo commit 9c3c4ba is after a47bf1a so I have your fix. Either way, I'm now testing with a47bf1a. Do you mean to encode the ssid? I'm using python 2.7.13.

**Comment by nicolargo** [comment]
Strange, can you show me the result of the following command:

```
# python
>>> import locale
>>> print(locale.getpreferredencoding()) 
```

**Comment by jkleve** [comment]
The result of the above python code gives
`'UTF-8'`

Commit d367cc0 works and solves my issue. Thank you.

Do note that the wifi strength is now about one tab closer to the ssid & encryption. This is only for the ssid that is giving us issues here. It seems the `u'\U0001f4a9'` character is slightly messing up the format of the line.

**Comment by jkleve** [comment]
See [this link](https://i.imgur.com/L5hezUI.png) to better understand what I'm saying. 

Feel free to close this issue. I just wanted to bring this to your attention. I could look into this formatting issue too when I have some time.

**Comment by nicolargo** [comment]
Ok thanks @jkleve !
