### ISSUE TITLE
ip plugin empty interface

### ISSUE THREAD

**Issue by gyakovlev** [nicolargo/glances#1509]
## Description
ip plugin has multiple issues with no interfaces defined.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.1 with psutil v5.6.1
* Operating System (lsb_release -a): Gentoo current
#### Logs

tests are running in empty network namespace, probably it triggers the following issues:
```shell-session
running test

Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
```
I believe this is because of https://github.com/nicolargo/glances/commit/f08abbfb6c7841d135ce72972d79dba89f7d11be#diff-351a7e7d7317e2c261dfd3d4d71312bd 

also test fails itself now, it was fine in 3.1.0 under empty network namespace an no interfaces are seen.
3.1.1
```shell-session
ERROR: test_012_ip (__main__.TestGlances)
Check IP plugin.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unitest.py", line 197, in test_012_ip
    stats_grab = stats.get_plugin('ip').get_raw()
AttributeError: 'NoneType' object has no attribute 'get_raw'
```

3.1.0
```shell-session
==============================================================================
INFO: [TEST_012] Check IP stats
INFO: IP stats: {}
```

affects runtime as well, with no network interfaces glances fails.

easy reproducer

```sh
unshare -n glances
```

3.1.0 will work
3.1.1 will crash

```python
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/glances", line 11, in <module>
    load_entry_point('Glances==3.1.1', 'console_scripts', 'glances')()
  File "/usr/lib64/python3.6/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib64/python3.6/site-packages/glances/__init__.py", line 109, in start
    mode.serve_forever()
  File "/usr/lib64/python3.6/site-packages/glances/standalone.py", line 149, in serve_forever
    loop = self.__serve_forever()
  File "/usr/lib64/python3.6/site-packages/glances/standalone.py", line 136, in __serve_forever
    ret = not self.screen.update(self.stats, duration=adapted_refresh)
  File "/usr/lib64/python3.6/site-packages/glances/outputs/glances_curses.py", line 980, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib64/python3.6/site-packages/glances/outputs/glances_curses.py", line 955, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib64/python3.6/site-packages/glances/outputs/glances_curses.py", line 580, in display
    self.__display_header(__stat_display)
  File "/usr/lib64/python3.6/site-packages/glances/outputs/glances_curses.py", line 638, in __display_header
    self.get_stats_display_width(stat_display["uptime"]) + 1)
KeyError: 'ip'
```

which, I believe is because of https://github.com/nicolargo/glances/commit/a55092e7601ee39324acb5463bd0a9dd4b64f4c0#diff-351a7e7d7317e2c261dfd3d4d71312bd

**Comment by nicolargo** [comment]
Corrected in https://github.com/nicolargo/glances/issues/1528

**Comment by primeos** [comment]
I'm still getting the

```
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
```

error message for Glances 3.1.2 inside of the Nix build sandbox, which uses network namespaces as well.

It isn't a big problem for me (only have to disable the IP module check during the build and it works outside of the build sandbox), but it seemed like a good idea to note it here in case it matters.

Version 3.1.0 was still fine:
```
Unitary tests for Glances 3.1.0

[...]

==============================================================================
INFO: [TEST_012] Check IP stats
INFO: IP stats: {}

```

While 3.1.1:
```
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
s.sssss.....E............
======================================================================
ERROR: test_012_ip (__main__.TestGlances)
Check IP plugin.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unitest.py", line 202, in test_012_ip
    stats_grab = stats.get_plugin('ip').get_raw()
AttributeError: 'NoneType' object has no attribute 'get_raw'

----------------------------------------------------------------------
Ran 25 tests in 0.041s

FAILED (errors=1, skipped=6)
Unitary tests for Glances 3.1.1
```

and 3.1.2:
```
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
s.sssss.....E............
======================================================================
ERROR: test_012_ip (__main__.TestGlances)
Check IP plugin.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unitest.py", line 202, in test_012_ip
    stats_grab = stats.get_plugin('ip').get_raw()
AttributeError: 'NoneType' object has no attribute 'get_raw'

----------------------------------------------------------------------
Ran 25 tests in 0.043s

FAILED (errors=1, skipped=6)
Unitary tests for Glances 3.1.2
```

cause problems with the IP plugin (as @gyakovlev already noted for 3.1.1 - the line numbers don't match because I already skip some of the other tests).

`iproute2` shows the following:
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
```

**Comment by gyakovlev** [comment]
@primeos as for me and gentoo build new version 3.1.2 corrected build and `unshare -n` crashes, so I can't confirm issues you have.
