### ISSUE TITLE
Error with IP Plugin : object has no attribute

### ISSUE THREAD

**Issue by in2out** [nicolargo/glances#1528]
I have a problem (centos 7.2)

xxxxx# glances
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')

xxxxx# glances  -V
Glances v3.1.1 with psutil v5.6.3

it cause below part.

plugins/glances_ip.py
return  ', '.join(set([x.strip() for x in ip.split(',')]))

ip is none...

**Comment by nicolargo** [comment]
Corrected by last commit.

THanks for the issue report.

**Comment by Globegitter** [comment]
@nicolargo I am on Ubuntu 19.10 with python 3.7 and getting the issue with glances 3.1.2:

```
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
Exception ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
  File "/home/markus/.local/lib/python3.7/site-packages/glances/__init__.py", line 68, in __signal_handler
    end()
  File "/home/markus/.local/lib/python3.7/site-packages/glances/__init__.py", line 83, in end
    sys.exit(0)
SystemExit: 0
```

Any idea why the issue could still show up? Or how to work around that.

**Comment by Globegitter** [comment]
Ah yes, it works fine without the plugin so at least I can start up glances :)

**Comment by NickWaterton** [comment]
Ubuntu 18.04, python 3.6, Glances 3.1.3 psutil 5.6.7 has the same issue. Starts with ip plugin disabled.

**Comment by nicolargo** [comment]
The DEVELOP branch has a new patch.

It solve this second issue concerning the IP plugin initialisation .

**Comment by maxnbk** [comment]
experienced this issue, patched 3.1.3 (with psutil 5.6.7) with commit and works fine.

**Comment by davidmaxwaterman** [comment]
I'm seeing this with glances v3.1.3-1 on Ubuntu Ubuntu 20.04.1 LTS. Any idea how to fix it?

**Comment by davidmaxwaterman** [comment]
Still getting this. Any chance it could be reopened?
```
10:59:32 ~$ glances
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
^C^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 68, in __signal_handler
    end()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 83, in end
    sys.exit(0)
SystemExit: 0
10:59:41 ~$ dpkg -l glances
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  glances        3.1.3-1      all          Curses-based monitoring tool
11:02:29 ~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
11:03:12 ~$ date
Tue 20 Oct 11:03:18 CST 2020
11:03:18 ~$ glances --version
Glances v3.1.3 with psutil v5.5.1
11:11:17 ~$
```

**Comment by davidmaxwaterman** [comment]
FYI, it seems it is 'soon...' (on 4 Mar):
```Will be available in Glances 3.1.4 (soon...)```
https://github.com/nicolargo/glances/issues/1615

**Comment by nicolargo** [comment]
Patch done in the develop branch.

Thanks for the issue report.

**Comment by davidmaxwaterman** [comment]
BTW, it seems like there's a 'meta' issue that is revealed by this bug - when it 'bombs out', it causes the terminal to become garbled so that anything typed is invisible and such like, requiring the user to type the command 'reset' in order to get it back to normal. It'd probably be a good idea if this didn't happen and the terminal remained 'ok'.

**Comment by sebmpluriad** [comment]
I have the same pb. on Ubuntu 20.04. :

```python
$ lsb_release -sd
Ubuntu 20.04.5 LTS
$ glances --version
Glances v3.1.3 with psutil v5.5.1
$ glances
Error while initializing the ip plugin ('NoneType' object has no attribute 'split')
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.3', 'console_scripts', 'glances')()
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python3/dist-packages/glances/__init__.py", line 112, in start
    mode.serve_forever()
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 151, in serve_forever
    loop = self.__serve_forever()
  File "/usr/lib/python3/dist-packages/glances/standalone.py", line 138, in __serve_forever
    ret = not self.screen.update(self.stats, duration=adapted_refresh)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 982, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 957, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 581, in display
    self.__display_header(__stat_display)
  File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 646, in __display_header
    self.display_plugin(stat_display["ip"])
KeyError: 'ip'
$ echo $?
1
```

**Comment by RazCrimson** [comment]
@sebmpluriad 

Do you have a custom config file?

If so could you make sure that the below keys either have valid values or have them commented.
Don't have keys like `key=  `
```
[ip]
disable=False
public_refresh_interval=300
public_ip_disabled=False
censys_url=https://search.censys.io/api
# censys_username=<censys_api_id>
#censys_password=<censys_secret>
censys_fields=location:continent,location:country,autonomous_system:name
```

**Comment by sebmpluriad** [comment]
@RazCrimson Hi, I don't even know what censys is ? Where would that custom config file be ?
