### ISSUE TITLE
Docker nicolargo/glances:latest missing arm builds?

### ISSUE THREAD

**Issue by oester** [nicolargo/glances#1746]
I was trying out glances on my raspberry pi and noted that using nicolargo/glances:latest pulls in the x86 build, as that's the only one on docker.io with that tag. nicolargo/glances:dev does have the arm builds, but using that with the the Web interface, I don't see any docker stats even when I start it correctly:

docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host nicolargo/glances:dev

I do see the hosts stats tho. Works just great on my Linux-x86 system.

**Comment by nicolargo** [comment]
Should be corrected by latest commit on the develop branch.

Image available for testing on https://hub.docker.com/repository/docker/nicolargo/glances

**Comment by oester** [comment]
Hmm, I pulled nicolargo/glances:dev but still can't see the docker containers on my Raspberry Pi.
