### ISSUE TITLE
KeyError: 'syscalls' and terminal layout broken

### ISSUE THREAD

**Issue by hugovk** [nicolargo/glances#1956]
**Describe the bug**

**To Reproduce**
1. Start Glances with no options
2. See error
3. Plus my terminal (iTerm2 3.4.12) no longer shows a cursor and the layout is wrong, the newlines are replaced with long indents?

```
                    Traceback (most recent call last):
                                                        File "/Library/Frameworks/Python.framework/Versions/3.10/bin/glances", line 8, in <module>
                                                                                                                                                      sys.exit(main())
                  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/__init__.py", line 150, in main
                                                                                                                                                   start(config=core.get_config(), args=core.get_args())
                                                    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/__init__.py", line 115, in start
                                mode.serve_issue()
                                                    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/standalone.py", line 128, in serve_issue
                                        ret = not self.screen.update(self.stats)
                                                                                  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/outputs/glances_stdout_issue.py", line 94, in update
                                                                                  self.print_version()
                                                                                                        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/outputs/glances_stdout_issue.py", line 81, in print_version
                                                                                                               sys.stdout.flush()
                                                                                                                                 BrokenPipeError: [Errno 32] Broken pipe
                  Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
Traceback (most recent call last):
                                    File "/Library/Frameworks/Python.framework/Versions/3.10/bin/glances", line 8, in <module>
                                                                                                                                  sys.exit(main())
                                                                                                                                                    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/__init__.py", line 150, in main
                                                                                                                               start(config=core.get_config(), args=core.get_args())
Traceback (most recent call last):
                                    File "/Library/Frameworks/Python.framework/Versions/3.10/bin/glances", line 8, in <module>
                                                                                                                                  sys.exit(main())
                                                                                                                                                    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/__init__.py", line 150, in main
                                                                                                  start(config=core.get_config(), args=core.get_args())
                                                                                                                                                         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/__init__.py", line 118, in start
                                                                                                        mode.serve_forever()
                                                                                                                              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/standalone.py", line 173, in serve_forever
                                                                                       while self.__serve_once():
                                                                                                                   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/standalone.py", line 158, in __serve_once
                                                                           ret = not self.screen.update(self.stats,
                                                                                                                     File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/outputs/glances_curses.py", line 1085, in update
                                                                                    self.flush(stats, cs_status=cs_status)
                                                                                                                            File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/outputs/glances_curses.py", line 1060, in flush
                                                                                          self.display(stats, cs_status=cs_status)
                                                                                                                                    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/outputs/glances_curses.py", line 585, in display
                                                                                                   __stat_display = self.__get_stat_display(stats, layer=cs_status)
                                                                                                                                                                     File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/outputs/glances_curses.py", line 558, in __get_stat_display
                                                                                                                                               ret[p] = stats.get_plugin(p).get_stats_display(args=self.args,
                            File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 939, in get_stats_display
     'msgdict': self.msg_curse(args),
                                       File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/plugins/glances_cpu.py", line 351, in msg_curse
     ret.extend(self.curse_add_stat('syscalls', width=15, header='  '))
                                                                         File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1008, in curse_add_stat
                                                if 'short_name' in self.fields_description[key]:
                                                                                                KeyError: 'syscalls'
                                                                                                                    %
```

**Expected behavior**

Glances runs with no errors and leaves the terminal working normally.

**Screenshots**

Running `glances`:

![image](https://user-images.githubusercontent.com/1324225/142758130-1942569d-c546-4ba4-985e-fd567e021af0.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.01
 - Python 3.10 and 3.9
 - Glances v3.2.4 with PsUtil v5.8.0 and Glances v3.2.4.1 with PsUtil v5.8.0
 - Glances logs file [output of tail -10 <glances logs file>]

```console
$ tail -10 /Users/hugo/.local/share/glances/glances.log
2021-11-21 12:15:43,103 -- INFO -- Start GlancesStandalone mode
                                                               2021-11-21 12:15:43,240 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
                                                                                                                                                                            2021-11-21 12:15:43,247 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
                                                                                                                    2021-11-21 12:15:43,248 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
                                             2021-11-21 12:15:43,250 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
                                                                                                                                                               2021-11-21 12:15:43,253 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
                                                                                          2021-11-21 12:15:43,265 -- WARNING -- Sparklines module not found (No module named 'sparklines')
       2021-11-21 12:15:43,268 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
                                                                                                                          2021-11-21 12:15:43,275 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
                                                 2021-11-21 12:15:43,275 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
                                                                                                                                                       %
```

Let's `cat` instead:

```
$ cat /Users/hugo/.local/share/glances/glances.log
2021-11-21 12:12:28,616 -- WARNING -- PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
2021-11-21 12:12:28,617 -- INFO -- Start Glances 3.2.4.1
2021-11-21 12:12:28,617 -- INFO -- CPython 3.10.0 (/Library/Frameworks/Python.framework/Versions/3.10/bin/python3) and psutil 5.8.0 detected
2021-11-21 12:12:28,641 -- INFO -- Start GlancesStandalone mode
2021-11-21 12:12:28,723 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2021-11-21 12:12:28,729 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
2021-11-21 12:12:28,729 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
2021-11-21 12:12:28,731 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2021-11-21 12:12:28,733 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2021-11-21 12:12:28,741 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2021-11-21 12:12:28,743 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2021-11-21 12:12:28,749 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2021-11-21 12:12:28,749 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2021-11-21 12:13:01,487 -- WARNING -- PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
2021-11-21 12:13:01,488 -- INFO -- Start Glances 3.2.4.1
2021-11-21 12:13:01,488 -- INFO -- CPython 3.10.0 (/Library/Frameworks/Python.framework/Versions/3.10/bin/python3) and psutil 5.8.0 detected
2021-11-21 12:13:03,480 -- WARNING -- PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
2021-11-21 12:13:03,481 -- INFO -- Start Glances 3.2.4.1
2021-11-21 12:13:03,481 -- INFO -- CPython 3.10.0 (/Library/Frameworks/Python.framework/Versions/3.10/bin/python3) and psutil 5.8.0 detected
```

 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

```console
$ glances --issue
======================================================================================================================================================
Glances 3.2.4.1 (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glances/__init__.py)
                                                                                                                     Python 3.10.0 (/Library/Frameworks/Python.framework/Versions/3.10/bin/python3)
                                             PsUtil 5.8.0 (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/psutil/__init__.py)
        ======================================================================================================================================================
        alert         [OK]    0.00004s [[1637489650.0, -1, 'WARNING', 'LOAD', 1.194580078125, 1.194580078125, 1.194580078125, 1.194580078125, 1, [],
                                                                                                                                                    amps          [OK]    0.00012s []
                               cloud         [OK]    0.00006s {}
                                                                connections   [OK]    0.00018s {}
                                                                                                 core          [OK]    0.00010s {'phys': 2, 'log': 4}
                                                                                                                                                     cpu           [OK]    0.00034s {'total': 14.9, 'user': 7.9, 'nice': 0.0, 'system': 7.0, 'idle': 85.1, 'time_since_update': 3.179678916931152
                                                                                                                                           diskio        [OK]    0.00099s key=disk_name [{'time_since_update': 3.1799638271331787, 'disk_name': 'disk0', 'read_count': 57, 'write_count
                                                                                                                                 docker        [OK]    0.00014s []
            folders       [OK]    0.00005s []
                                             fs            [OK]    0.00076s key=mnt_point [{'device_name': '/dev/disk1s5s1', 'fs_type': 'apfs', 'mnt_point': '/', 'size': 250790436864, '
                                   gpu           [OK]    0.00004s []
                                                                    help          [OK]    0.00001s None
                                                                                                       ip            [OK]    0.00012s {}
                                                                                                                                        irq           [OK]    0.00005s []
                   load          [OK]    0.00007s {'min1': 2.33642578125, 'min5': 4.0185546875, 'min15': 4.76171875, 'cpucore': 4}
                                                                                                                                  mem           [OK]    0.00014s {'total': 17179869184, 'available': 5604433920, 'percent': 67.4, 'used': 11575435264, 'free': 5604433920, 'ac
                                                                                                                        memswap       [OK]    0.00009s {'total': 2147483648, 'used': 1021575168, 'free': 1125908480, 'percent': 47.6, 'sin': 852381872128, 'sout': 1
                                                                                                              network       [OK]    0.00321s key=interface_name [{'interface_name': 'lo0', 'alias': None, 'time_since_update': 3.020667791366577, 'cumulat
                                                                                                    now           [OK]    0.00004s 2021-11-21 12:14:13 EET
    percpu        [OK]    0.00042s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 25.5, 'user': 12.9, 'system': 12.6, 'idle': 7
                                                                                                                                                ports         [OK]    0.00056s []
                           processcount  [OK]    0.12981s {'total': 618, 'running': 616, 'sleeping': 0, 'thread': 1994, 'pid_max': 0}
                                                                                                                                     processlist   [OK]    0.00056s key=pid [{'pid': 18933, 'memory_percent': 1.414632797241211, 'ppid': 1, 'cpu_times': pcputimes(user=14298.983
                                                                                                                           psutilversion [OK]    0.00006s (5, 8, 0)
             quicklook     [OK]    0.00017s {'cpu': 14.9, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 25.5, 'user': 12.9, 'system': 12.6,
   raid          [OK]    0.00003s {}
                                    sensors       [OK]    0.00001s key=label [{'label': 'Battery', 'value': 88, 'unit': '%', 'type': 'battery', 'key': 'label'}]
          smart         [N/A]
                             system        [OK]    0.00001s {'os_name': 'Darwin', 'hostname': 'Hugos-MBP.local', 'platform': '64bit', 'os_version': '12.0.1', 'hr_name':
                   uptime        [OK]    0.00006s {'seconds': 2138597}
                                                                      wifi          [OK]    0.00002s []
                                                                                                      


```

**Additional context**

Downgrading to `Glances v3.2.3.1 with PsUtil v5.8.0` fixes Glances, and after Glances the terminal cursor is back, but the layout is still broken (opening a new terminal tab is fine).

**Comment by hugovk** [comment]
Git bisecting between v3.2.3.1 and v3.2.4:

73f091f2d277db56fe60223b2b6ccf14c91a1392 is the first bad commit
                                                                commit 73f091f2d277db56fe60223b2b6ccf14c91a1392
                                                                                                                                Date:   Sun Aug 29 17:50:07 2021 +0200

                                                           Refactor CPU Curses code

                                                                                    glances/plugins/glances_cpu.py    | 114 +++++++++++++-------------------------
                            glances/plugins/glances_plugin.py |  94 ++++++++++++++++++++++++++++++-
                                                                                                    2 files changed, 129 insertions(+), 79 deletions(-)

**Comment by nicolargo** [comment]
Hi @hugovk 

please can you show me the result of the following comamnd line on your system ?

```
$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.cpu_stats()
scpustats(ctx_switches=1297153789, interrupts=545095417, soft_interrupts=371678022, syscalls=0)
>>> 

```

Thanks in advance !

**Comment by nicolargo** [comment]
@hugovk Should be corrected by the latest commit. Can you test the develop branch ?

**Comment by robinbowes** [comment]
Did you push to test.pypi.org? I just tried that and am still getting the error.

**Comment by nicolargo** [comment]
Also avalaible in the patch version 3.2.4.2.

**Comment by robinbowes** [comment]
> Did you push to test.pypi.org? I just tried that and am still getting the error.

Nope, you didn't, but confirm fixed when installed from `develop` branch.

**Comment by nicolargo** [comment]
The build process is long (more or less one hour...).

So it will be release and corrected in Glances 3.2.4.2.

Thanks again for the report !

**Comment by hugovk** [comment]
Confirmed Glances 3.2.4.2 works, thanks for the quick fix!
