### ISSUE TITLE
Web UI truncates the days part of CPU time counter of the process list

### ISSUE THREAD

**Issue by hrandib** [nicolargo/glances#2108]
Hi @nicolargo
Web UI version of glances doesn't show the correct hours counter in the process list. e.g. if the process CPU time equals 31h20:00 the Web UI shows 7h20:00 (days truncated: 31 - 24 = 7).

**To Reproduce**
To reproduce you can check any process that reached 24h threshold in the process list in the Web UI

**Expected behavior**
CPU time row values match in both console UI and web UI for long-living processes

**Screenshots**
Web UI:
![image](https://user-images.githubusercontent.com/17005110/185359194-a1920886-e8e4-4031-bd10-f3a02889afa9.png)
The terminal at the same time:
![image](https://user-images.githubusercontent.com/17005110/185359359-e45286b9-7b15-45f1-b684-9531837ea6c4.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04 64bit / Linux 5.15.0-43-generic
 - Glances v3.2.7 with PsUtil v5.9.1
 - Glances logs file [output of tail -10 <glances logs file>]
2022-08-18 12:19:45,569 -- ERROR -- docker plugin - Cannot get Docker version (('Connection aborted.', FileNotFoundError(2, 'No such file or directory')))
2022-08-18 12:19:46,191 -- INFO -- Glances stopped (key pressed: CTRL-C)
2022-08-18 12:19:50,057 -- INFO -- Start Glances 3.2.7
2022-08-18 12:19:50,058 -- INFO -- CPython 3.8.10 (/usr/bin/python) and psutil 5.9.1 detected
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)
[glances-issue.txt](https://github.com/nicolargo/glances/files/9372236/glances-issue.txt)

**Additional context**
It seems the problem may be even broader, the process with PID 567405 from screenshots also didn't match

**Comment by nicolargo** [comment]
Node for WebUI dev: Something to do here: https://github.com/nicolargo/glances/blob/v3.2.7/glances/outputs/static/js/filters.js#L108

**Comment by nicolargo** [comment]
@hrandib corrected in the develop branch.
Thanks for the bug report !

**Comment by hrandib** [comment]
Hello @nicolargo, it seems that it still persists.
![image](https://user-images.githubusercontent.com/17005110/197892039-16dad0a2-5a6f-48a5-80a4-118d0119c2e9.png)
![image](https://user-images.githubusercontent.com/17005110/197892200-8bd69cd2-357e-4759-a7c0-bc9b0fbdc493.png)
