### ISSUE TITLE
TERM setting causes glances to crash

### ISSUE THREAD

**Issue by monochromec** [nicolargo/glances#2598]
**Describe the bug**
glances crashes on bookworm with TERM set to `xterm-color` or `linux` with the following traceback:
```
Traceback (most recent call last):
File "venvs/glances_org/bin/glances", line 8, in <module>                                                                                                                       sys.exit(main())                                                                                                                                              ^^^^^^                                                                                                                                                       File "venvs/glances/glances/__init__.py", line 183, in main
              start(config=core.get_config(), args=core.get_args())
File "venvs/glances/glances/__init__.py", line 106, in start
mode = GlancesMode(config=config, args=args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "venvs/glances/glances/standalone.py", line 106, in __init__                                                                                                                                                               self.screen = GlancesCursesStandalone(config=config, args=args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "venvs/glances/glances/outputs/glances_curses.py", line 167, in __init__                                                                                                                                                                                              self._init_colors()
       File "venvs/glances/glances/outputs/glances_curses.py", line 301, in _init_colors                                                                                                                  curses.init_color(12, 500, 500, 500)                                                                                                                  ValueError: Color number is greater than COLORS-1 (7).
```
**To Reproduce**
1. Run glances with corresponding TERM setting.

**Expected behavior**
glances to run w/o issue.

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
 - Glances & psutil versions: Glances v4.0.0_beta01 with PsUtil v5.9.6 (develop branch)
 - How do you install Glances (Pypi package, script, package manager, source): `gh clone` in venv development
 - Glances test (only available with Glances 3.1.7 or higher):

 Cf. [gist](https://gist.github.com/monochromec/9c273f4782b1650cd347f4adff5c007e)

**Additional context**

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location):  Standard conf file from the Bookworm package (3.3.1.1+dfsg-1), cf. [gist](https://gist.github.com/monochromec/19ca56f94a64fba8b702851236da4b3b )
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging): Cf. [gist](https://gist.github.com/monochromec/963be06f62c081edb2c28545539e0a01 )

**Comment by monochromec** [comment]
Work-around: set TERM to xterm-256color

**Comment by nicolargo** [comment]
Corrected by the last commit in the develop branch. 

Also add a colors overview in the help screen.

![image](https://github.com/nicolargo/glances/assets/776747/64da846d-2a7e-42d4-ab01-524e81d684f4)

**Comment by metayan** [comment]
Still crashes on similar setup with `tmux` where `TERM` is `tmux-256color`.
Setting `TERM` to `linux`, `xterm`, `xterm-256color` or `tmux` works.
On current `develop` branch, i.e. 36ed96b05a6627aa8eeb4f8afbd7a268ce0aa572 .
Has been an issue since 30cc9f3e0e3b7d427e1d7c9a8a58a536288f7210 .

Removing https://github.com/nicolargo/glances/blob/36ed96b05a6627aa8eeb4f8afbd7a268ce0aa572/glances/outputs/glances_curses.py#L317
solves the issue.
