### ISSUE TITLE
Cannot set warning/critical temperature for a specific sensor

### ISSUE THREAD

**Issue by FrancoisMentec** [nicolargo/glances#3102]
The following config file does not work:
```
[sensors]
temperature_core_Tctl_warning=40
temperature_core_Tctl_critical=95
```
API:
```
[
  {
    "label": "Composite",
    "unit": "C",
    "value": 49,
    "warning": 83,
    "critical": 87,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Sensor 1",
    "unit": "C",
    "value": 70,
    "warning": 65261,
    "critical": 65261,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Sensor 2",
    "unit": "C",
    "value": 43,
    "warning": 65261,
    "critical": 65261,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Tccd1",
    "unit": "C",
    "value": 55,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Tctl",
    "unit": "C",
    "value": 68,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "edge",
    "unit": "C",
    "value": 52,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "mt7921_phy0 0",
    "unit": "C",
    "value": 40,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  }
]
```
As you can see warning and critical are null for Tctl.

The following config file does work:
```
[sensors]
temperature_core_warning=40
temperature_core_critical=95
```
Temps are now displayed in purple in the web interface when above 40°C, but the API still doesn't provide the temperature thresholds:
```
[
  {
    "label": "Composite",
    "unit": "C",
    "value": 47,
    "warning": 83,
    "critical": 87,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Sensor 1",
    "unit": "C",
    "value": 68,
    "warning": 65261,
    "critical": 65261,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Sensor 2",
    "unit": "C",
    "value": 41,
    "warning": 65261,
    "critical": 65261,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Tccd1",
    "unit": "C",
    "value": 46,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "Tctl",
    "unit": "C",
    "value": 55,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "edge",
    "unit": "C",
    "value": 47,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  },
  {
    "label": "mt7921_phy0 0",
    "unit": "C",
    "value": 38,
    "warning": null,
    "critical": null,
    "type": "temperature_core",
    "key": "label"
  }
]
```
I want to set the warning an critical temperature returned by the API for the Tctl sensor and ideally only it. I tried many syntax (temperature_Tctl_warning, temperature_tctl_warning, temperature_core_tctl_warning, ...) in the config file, but so far no luck. The documentation has not been helpful either: https://glances.readthedocs.io/en/latest/aoa/sensors.html

My glances version:
```shell
root@homelab:~/.config/glances# glances --version
Glances version:        4.3.0.8
Glances API version:    4
PsUtil version:         6.1.1
Log file:               /root/.local/share/glances/glances.log
```
Running on Debian 12 in a proxmox host.

Please send help :-(

**Comment by nicolargo** [comment]
Hi @FrancoisMentec thanks for the issue report.

Also reproduced on my side:

```
[sensors]
disable=False
# Sensors core thresholds (in Celsius...)
# By default values are grabbed from the system
# Overwrite thresholds for a specific sensor
temperature_core_Ambient_careful=45
temperature_core_Ambient_warning=65
temperature_core_Ambient_critical=80
```

Logs:

```
2025-02-16 18:53:52,862 -- DEBUG -- Load limit: sensors_temperature_core_ambient_careful = 45.0
2025-02-16 18:53:52,862 -- DEBUG -- Load limit: sensors_temperature_core_ambient_warning = 65.0
2025-02-16 18:53:52,862 -- DEBUG -- Load limit: sensors_temperature_core_ambient_critical = 80.0
2025-02-16 18:53:53,270 -- DEBUG -- PluginModel glances.plugins.sensors update return [{'label': 'Ambient', 'unit': 'C', 'value': 35, 'warning': 0, 'critical': None, 'type': <SensorType.CPU_TEMP: 'temperature_core'>, 'key': 'label'},...
```

Not displayed:

![Image](https://github.com/user-attachments/assets/f4cb0ac9-93c5-4997-af4a-8e99816406af)

Note for investigation:
- tested without success with temperature_core_ambient_careful (replace Ambient with ambient)
- have a look on 'type': <SensorType.CPU_TEMP: 'temperature_core'>...

**Comment by nicolargo** [comment]
Should be corrected in the develop branch.

@FrancoisMentec Can you please test it ?

**Comment by AsgerMogensen** [comment]
I still experience the same problems running the latest version in a docker container on a Ubuntu 24.04 server.

The config:
```
[sensors]
disable=False
temperature_core_careful=45
temperature_core_warning=65
temperature_core_critical=80
```


API:
```
{
   "temperature_core":[
      {
         "label":"Core 0",
         "unit":"C",
         "value":30,
         "warning":100,
         "critical":100,
         "type":"temperature_core",
         "key":"label"
      },
      {
         "label":"Core 1",
         "unit":"C",
         "value":30,
         "warning":100,
         "critical":100,
         "type":"temperature_core",
         "key":"label"
      },
      {
         "label":"Package id 0",
         "unit":"C",
         "value":33,
         "warning":100,
         "critical":100,
         "type":"temperature_core",
         "key":"label"
      },
      {
         "label":"acpitz 0",
         "unit":"C",
         "value":33,
         "warning":null,
         "critical":null,
         "type":"temperature_core",
         "key":"label"
      },
      {
         "label":"iwlwifi_1 0",
         "unit":"C",
         "value":43,
         "warning":null,
         "critical":null,
         "type":"temperature_core",
         "key":"label"
      },
      {
         "label":"pch_skylake 0",
         "unit":"C",
         "value":31,
         "warning":null,
         "critical":null,
         "type":"temperature_core",
         "key":"label"
      }
   ]
}
```

The change do show up in the log:
```
2025-07-02 07:50:45,980 -- DEBUG -- Load limit: sensors_temperature_core_careful = 45.0
2025-07-02 07:50:45,980 -- DEBUG -- Load limit: sensors_temperature_core_warning = 65.0
2025-07-02 07:50:45,981 -- DEBUG -- Load limit: sensors_temperature_core_critical = 80.0
```

The change is also displayed in the web app:
<img width="370" alt="Image" src="https://github.com/user-attachments/assets/65190322-c072-415d-b76a-45c28f413013" />

Version:
```
Glances version:	4.3.1
Glances API version:	4
PsUtil version:		7.0.0
Log file:		/tmp/glances-root.log
```

I have confirmed that other config changes works:
```
[sensors]
disable=False
```
