### ISSUE TITLE
CSV export: Data lines with more columns than expected

### ISSUE THREAD

**Issue by mattpoel** [nicolargo/glances#847]
#### Description

I was running glances with CSV export on a Windows 2008 Server R2 SP1 64-Bit to collect data for 24 hours. The following command was used for the data collection:

```
glances.exe --export-csv C:\tmp\glances_out.csv -1 -b --diskio-iops -t 1 -q
```

During analysis of the collected data, I found lines where glances is writing too much columns for the snapshot lines. Please find an example snippet below (I've removed the first columns for better readability):

```
diskio_PhysicalDrive1_disk_name,diskio_PhysicalDrive1_key,diskio_PhysicalDrive1_read_bytes,processcount_sleeping,processcount_running,processcount_thread,processcount_total,cpu_user,cpu_system,cpu_total,cpu_idle
PhysicalDrive1,disk_name,212992,0,131,1553,131,1.5,49.2,0.0,49.2
PhysicalDrive1,disk_name,212992,0,132,1555,132,1,3.0,0.0,50.0,100.0
```
![glances_out_csv_in_excel](https://cloud.githubusercontent.com/assets/15014728/14506094/70aa62fa-01bc-11e6-8bee-7f4ef75546eb.png)

Somehow it seems that for the total cpu usage, glances is writing too many column values (11 columns for the header row and nearly all data rows / 12 columns for some data rows). Up to processcount_total all the data looks fine in the second line.

Please let me know if you should require more information to debug this issue. Thanks a lot in advance!
#### Versions

* Glances (glances -V): Glances v2.6.1
* PSutil (glances -V): psutil v4.1.0
* Operating System (lsb_release -a): Windows 2008ServerR2 SP1 64bit

**Comment by nicolargo** [comment]
Also reproduce on Ubuntu with Glances 2.6.1.

Bug confirmed.

**Comment by mattpoel** [comment]
Thanks for the fast response!

I think there is a general problem with the total cpu usage calculation. Per core data looks fine, but somehow the values do not add up in the total cpu usage calculation:

```
cpu_system + cpu_user <> cpu_total
cpu_total + cpu_idle <> 100
```

Should I create another issue for this or am I missing something?

**Comment by nicolargo** [comment]
Nope, the issue did not come from the CPU plugin.

Be aware that it is normal that cpu_system + cpu_user <> cpu_total. 

"""
        # Grab CPU stats using psutil's cpu_percent and cpu_times_percent
        # Get all possible values for CPU stats: user, system, idle,
        # nice (UNIX), iowait (Linux), irq (Linux, FreeBSD), steal (Linux 2.6.11+)
        # The following stats are returned by the API but not displayed in the UI:
        # softirq (Linux), guest (Linux 2.6.24+), guest_nice (Linux 3.2.0+)
        self.stats['total'] = cpu_percent.get()
        cpu_times_percent = psutil.cpu_times_percent(interval=0.0)
        for stat in ['user', 'system', 'idle', 'nice', 'iowait',
                     'irq', 'softirq', 'steal', 'guest', 'guest_nice']:
            if hasattr(cpu_times_percent, stat):
                self.stats[stat] = getattr(cpu_times_percent, stat)
"""

**Comment by mattpoel** [comment]
Yes, it's clear that on other OS I would have additional CPU stats like iowait, irq, etc. I thought that the CSV export provides all available stats from psutil for the OS it's running on (in this case Windows 2008R2) and therefore the values should add up to cpu_total. If this is not case, I will just calculate a cpu_other column based on `cpu_total - cpu_system - cpu_user = cpu_other`.

Do you know why `cpu_total + cpu_idle <> 100`?

**Comment by nicolargo** [comment]
@mattpoel Nope. 

Can you do the following:

    # python
    >>> psutil.cpu_times()

Nicolas

**Comment by nicolargo** [comment]
@mattpoel Concerning the CSV export issue. Can you test the latest DEVELOP branch version ? It should solve it.

**Comment by nicolargo** [comment]
@mattpoel : Any feedback ?

**Comment by arwhiz123** [comment]
I'm using latest build of glances .... CSV issue still reproduce
